version: '3.8'

volumes:
  db: {}

services:
  laravel:
    container_name: laravel
     image: <your_image_name>
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:13-alpine3.18
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
